#define IN_INTERRUPT 2  //PIN PARA EL SENSOR DE VIBRACIÓN (INTERRUPT)
#define OUT_DISABLE_POWER 4 //PIN QUE CONTROLA VDD
#define IN_DIAMETER A7  //PIN PARA EL SENSOR INFRARROJO DE DISTANCIA
#define IN_LINE A6   //PIN PARA EL SENSOR INFRARROJO QUE CUENTA LAS VUELTAS

#define SAMPLES 10  //No. Muestras del sensor analogo
#define T_FILTER 2  //mSeg sensando el sensor de línea